name: Secret Scanning with GitGuardian

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitguardian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Necesario para escanear todo el historial
      - name: Install ggshield
        run: pip install ggshield
      - name: Scan for secrets
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.SECRET_GIT_GUARDIAN }}
        run: ggshield secret scan repo . --exit-zero
